// portal/react-webapp/src/pages/sources/index.tsx
/**
 * Sources list page — Browse and manage registered data sources.
 */

import React, { useState } from 'react';
import Link from 'next/link';
import { useSources } from '@/hooks/useApi';
import type { SourceRecord, SourceStatus } from '@/types';

const STATUS_BADGES: Record<
  SourceStatus,
  { color: string; label: string }
> = {
  draft: { color: 'bg-gray-100 text-gray-800', label: 'Draft' },
  pending_approval: { color: 'bg-yellow-100 text-yellow-800', label: 'Pending' },
  approved: { color: 'bg-blue-100 text-blue-800', label: 'Approved' },
  provisioning: { color: 'bg-purple-100 text-purple-800', label: 'Provisioning' },
  active: { color: 'bg-green-100 text-green-800', label: 'Active' },
  paused: { color: 'bg-orange-100 text-orange-800', label: 'Paused' },
  decommissioned: { color: 'bg-red-100 text-red-800', label: 'Decommissioned' },
  error: { color: 'bg-red-100 text-red-800', label: 'Error' },
};

export default function SourcesPage() {
  const [domainFilter, setDomainFilter] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('');
  const { data: sources, isLoading, error, refetch } = useSources({
    domain: domainFilter || undefined,
    status: statusFilter || undefined,
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Data Sources</h1>
          <p className="mt-1 text-sm text-gray-500">
            Manage registered data sources and their pipelines
          </p>
        </div>
        <Link
          href="/sources/register"
          className="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-brand-600 rounded-md hover:bg-brand-700"
        >
          + Register Source
        </Link>
      </div>

      {/* Filters */}
      <div className="flex gap-4">
        <input
          type="text"
          value={domainFilter}
          onChange={(e) => setDomainFilter(e.target.value)}
          placeholder="Filter by domain..."
          className="px-3 py-2 border border-gray-300 rounded-md text-sm"
        />
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="px-3 py-2 border border-gray-300 rounded-md text-sm"
        >
          <option value="">All statuses</option>
          <option value="active">Active</option>
          <option value="pending_approval">Pending Approval</option>
          <option value="provisioning">Provisioning</option>
          <option value="error">Error</option>
          <option value="paused">Paused</option>
        </select>
      </div>

      {/* Error State */}
      {error ? (
        <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
          <svg className="mx-auto h-10 w-10 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
          </svg>
          <h3 className="mt-2 text-sm font-medium text-red-800">Failed to load sources</h3>
          <p className="mt-1 text-sm text-red-600">
            {error instanceof Error ? error.message : 'An unexpected error occurred.'}
          </p>
          <button
            onClick={() => refetch()}
            className="mt-4 inline-flex items-center px-4 py-2 text-sm font-medium text-red-700 bg-red-100 border border-red-300 rounded-md hover:bg-red-200"
          >
            Retry
          </button>
        </div>
      ) : isLoading ? (
        /* Loading State */
        <div className="flex items-center justify-center h-64">
          <div role="status" aria-label="Loading">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-brand-600" />
          </div>
        </div>
      ) : (
        /* Sources Table */
        <div className="bg-white shadow-sm rounded-lg border border-gray-200 overflow-hidden">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Name
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Type
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Domain
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Status
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Classification
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                  Updated
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {sources && sources.length > 0 ? (
                sources.map((source: SourceRecord) => {
                  const badge = STATUS_BADGES[source.status];
                  return (
                    <tr
                      key={source.id}
                      className="hover:bg-gray-50 cursor-pointer"
                    >
                      <td className="px-6 py-4 whitespace-nowrap">
                        <Link
                          href={`/sources/${source.id}`}
                          className="text-sm font-medium text-brand-600 hover:text-brand-800"
                        >
                          {source.name}
                        </Link>
                        <p className="text-xs text-gray-500">
                          {source.description?.substring(0, 60)}
                        </p>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {source.source_type.replace(/_/g, ' ')}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 capitalize">
                        {source.domain}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${badge.color}`}
                        >
                          {badge.label}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 uppercase">
                        {source.classification}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(source.updated_at).toLocaleDateString()}
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td
                    colSpan={6}
                    className="px-6 py-12 text-center text-gray-500"
                  >
                    No data sources found. Register your first source to get
                    started.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// _archived/static-webapp-svelte/src/routes/sources/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { listSources } from '$lib/api';
	import type { SourceRecord, SourceStatus } from '$lib/types';

	let sources: SourceRecord[] = $state([]);
	let loading = $state(true);
	let error: string | null = $state(null);

	// Filters
	let searchQuery = $state('');
	let filterDomain = $state('');
	let filterStatus = $state('');

	onMount(async () => {
		await loadSources();
	});

	async function loadSources() {
		loading = true;
		error = null;
		try {
			sources = await listSources({
				domain: filterDomain || undefined,
				status: filterStatus || undefined
			});
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load sources';
		} finally {
			loading = false;
		}
	}

	const filteredSources = $derived(
		sources.filter((s) => {
			if (!searchQuery) return true;
			const q = searchQuery.toLowerCase();
			return (
				s.name.toLowerCase().includes(q) ||
				s.source_type.toLowerCase().includes(q) ||
				s.owner.team.toLowerCase().includes(q) ||
				(s.description && s.description.toLowerCase().includes(q))
			);
		})
	);

	const domains = $derived([...new Set(sources.map((s) => s.owner.team))].sort());

	function statusBadgeClass(status: SourceStatus): string {
		switch (status) {
			case 'active':
				return 'badge-green';
			case 'pending':
			case 'provisioning':
				return 'badge-yellow';
			case 'error':
				return 'badge-red';
			case 'paused':
			case 'decommissioned':
				return 'badge-gray';
			default:
				return 'badge-blue';
		}
	}

	function formatDate(dateStr: string): string {
		return new Date(dateStr).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric'
		});
	}

	function formatSourceType(type: string): string {
		return type
			.split('_')
			.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
			.join(' ');
	}
</script>

<svelte:head>
	<title>Sources | CSA Portal</title>
</svelte:head>

<div class="space-y-6">
	<!-- Page Header -->
	<div class="flex items-center justify-between">
		<div>
			<h2 class="text-2xl font-bold text-gray-900">Data Sources</h2>
			<p class="mt-1 text-sm text-gray-500">Manage registered data sources</p>
		</div>
		<a href="/sources/register" class="btn-primary">
			<svg class="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
				<path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
			</svg>
			Register Source
		</a>
	</div>

	<!-- Filters -->
	<div class="card">
		<div class="flex flex-wrap gap-4">
			<!-- Search -->
			<div class="flex-1">
				<label for="search" class="sr-only">Search sources</label>
				<div class="relative">
					<svg class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
						<path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
					</svg>
					<input
						id="search"
						type="text"
						placeholder="Search sources by name, type, or domain..."
						bind:value={searchQuery}
						class="input-field pl-10"
					/>
				</div>
			</div>

			<!-- Domain Filter -->
			<div class="w-48">
				<select
					bind:value={filterDomain}
					onchange={() => loadSources()}
					class="input-field"
				>
					<option value="">All Domains</option>
					{#each domains as domain}
						<option value={domain}>{domain}</option>
					{/each}
				</select>
			</div>

			<!-- Status Filter -->
			<div class="w-40">
				<select
					bind:value={filterStatus}
					onchange={() => loadSources()}
					class="input-field"
				>
					<option value="">All Statuses</option>
					<option value="pending">Pending</option>
					<option value="provisioning">Provisioning</option>
					<option value="active">Active</option>
					<option value="paused">Paused</option>
					<option value="error">Error</option>
					<option value="decommissioned">Decommissioned</option>
				</select>
			</div>
		</div>
	</div>

	<!-- Sources Table -->
	{#if loading}
		<div class="flex items-center justify-center py-12">
			<div class="h-8 w-8 animate-spin rounded-full border-4 border-azure-200 border-t-azure-500"></div>
		</div>
	{:else if error}
		<div class="card border-red-200 bg-red-50">
			<p class="text-sm text-red-700">{error}</p>
			<button type="button" onclick={() => loadSources()} class="mt-2 text-sm font-medium text-red-800 underline">
				Retry
			</button>
		</div>
	{:else if filteredSources.length === 0}
		<div class="card py-12 text-center">
			<svg class="mx-auto h-12 w-12 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
				<path stroke-linecap="round" stroke-linejoin="round" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
			</svg>
			<h3 class="mt-4 text-sm font-medium text-gray-900">No sources found</h3>
			<p class="mt-1 text-sm text-gray-500">
				{searchQuery ? 'Try adjusting your search criteria.' : 'Get started by registering your first data source.'}
			</p>
			{#if !searchQuery}
				<a href="/sources/register" class="btn-primary mt-4">Register Source</a>
			{/if}
		</div>
	{:else}
		<div class="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm">
			<table class="min-w-full divide-y divide-gray-200">
				<thead class="bg-gray-50">
					<tr>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Source</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Type</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Team</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Classification</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Status</th>
						<th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">Created</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-gray-200">
					{#each filteredSources as source}
						<tr class="transition-colors hover:bg-gray-50">
							<td class="px-6 py-4">
								<div>
									<p class="text-sm font-medium text-gray-900">{source.name}</p>
									{#if source.description}
										<p class="text-xs text-gray-500 line-clamp-1">{source.description}</p>
									{/if}
								</div>
							</td>
							<td class="px-6 py-4 text-sm text-gray-600">{formatSourceType(source.source_type)}</td>
							<td class="px-6 py-4 text-sm text-gray-600">{source.owner.team}</td>
							<td class="px-6 py-4">
								<span class="badge-blue">{source.classification.toUpperCase()}</span>
							</td>
							<td class="px-6 py-4">
								<span class={statusBadgeClass(source.status)}>{source.status}</span>
							</td>
							<td class="px-6 py-4 text-sm text-gray-500">{formatDate(source.created_at)}</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
		<p class="text-sm text-gray-500">{filteredSources.length} source{filteredSources.length !== 1 ? 's' : ''}</p>
	{/if}
</div>
